/*
 * Copyright (c) 2017 Nova Ordis LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.novaordis.events.processing.output;

import io.novaordis.events.api.event.Event;

/**
 * @author Ovidiu Feodorov <ovidiu@novaordis.com>
 * @since 8/30/17
 */
public interface HeaderOutputStrategy {

    // Constants -------------------------------------------------------------------------------------------------------

    // Static ----------------------------------------------------------------------------------------------------------

    // Public ----------------------------------------------------------------------------------------------------------

    /**
     * Tells whether a header should be displayed for this event. If the method returns true, then the output
     * procedure must obtain the header and display it, unless the header generated by the format for the event is null.
     *
     * @exception IllegalArgumentException on null events.
     */
    boolean shouldDisplayHeader(Event e);

    /**
     * State update on whether a header was displayed or not for a specific event.
     *
     * @exception IllegalArgumentException on null events.
     */
    void headerDisplayed(Event e);

}
